// Mocks generated by Mockito 5.0.3 from annotations
// in text_marks_the_spot_app/test/functionality/authentication/apple_sign_in_available_test.dart.
// Do not manually edit this file.

import 'package:apple_sign_in/apple_sign_in.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:text_marks_the_spot_app/functionality/authentication/apple_sign_in_available.dart'
    as _i2;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [AppleSignInAvailable].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppleSignInAvailable extends _i1.Mock
    implements _i2.AppleSignInAvailable {
  MockAppleSignInAvailable() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [AppleSignIn].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppleSignIn extends _i1.Mock implements _i3.AppleSignIn {
  MockAppleSignIn() {
    _i1.throwOnMissingStub(this);
  }
}
